// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6tFlJkycaQBUOcU60toE3zbghRePQmfU',
    appId: '1:497620794729:web:03927198a949f9ee38d1f8',
    messagingSenderId: '497620794729',
    projectId: 'makanyuk-f8834',
    authDomain: 'makanyuk-f8834.firebaseapp.com',
    storageBucket: 'makanyuk-f8834.firebasestorage.app',
    measurementId: 'G-H8NCLWQRD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdL24j9_bm3TtPQ3yMS9XbKPDHqEI_RdI',
    appId: '1:497620794729:android:4068ecdabbee498138d1f8',
    messagingSenderId: '497620794729',
    projectId: 'makanyuk-f8834',
    storageBucket: 'makanyuk-f8834.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0f_zYz3yftRAYXIObiL4fP6j41B7b3fA',
    appId: '1:497620794729:ios:b18671b7c40615b438d1f8',
    messagingSenderId: '497620794729',
    projectId: 'makanyuk-f8834',
    storageBucket: 'makanyuk-f8834.firebasestorage.app',
    iosBundleId: 'com.example.demoModul2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0f_zYz3yftRAYXIObiL4fP6j41B7b3fA',
    appId: '1:497620794729:ios:b18671b7c40615b438d1f8',
    messagingSenderId: '497620794729',
    projectId: 'makanyuk-f8834',
    storageBucket: 'makanyuk-f8834.firebasestorage.app',
    iosBundleId: 'com.example.demoModul2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6tFlJkycaQBUOcU60toE3zbghRePQmfU',
    appId: '1:497620794729:web:0577d7c15144f0aa38d1f8',
    messagingSenderId: '497620794729',
    projectId: 'makanyuk-f8834',
    authDomain: 'makanyuk-f8834.firebaseapp.com',
    storageBucket: 'makanyuk-f8834.firebasestorage.app',
    measurementId: 'G-ENT4L5NKF9',
  );
}
